# Node.js

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# name: $(TeamProject)$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
name: $(Date:yyyyMMdd)$(Rev:-r)

variables:
  - group: Default Variable Group

trigger:
  - master
  - develop
  - feature/*
  - release/*

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: buildAndTest
    variables:
      YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn
    timeoutInMinutes: "20"
    displayName: Build and test
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '16.x'
        displayName: 'Install Node.js'
      - task: Cache@2
        inputs:
          key: 'yarn | "$(Agent.OS)" | yarn.lock'
          restoreKeys: |
            yarn | "$(Agent.OS)"
            yarn
          path: $(YARN_CACHE_FOLDER)
        displayName: Cache Yarn packages
      - script: yarn install --frozen-lockfile
        displayName: 'Yarn install'
      - script: yarn lint
        displayName: 'Yarn Lint'
      - script: yarn build
        displayName: 'Yarn build'
        env:
          RELATIVE_CI_SLUG: furystack/multiverse
          RELATIVE_CI_KEY: $(RELATIVE_CI_KEY)
      - script: yarn dockerize
        displayName: 'Create Docker images'
      - task: DockerCompose@0
        displayName: Start docker services
        inputs:
          action: Run services
          dockerComposeFile: '$(System.DefaultWorkingDirectory)/docker-compose.yml'
          projectName: $(Build.Repository.Name)
          detached: true
          buildImages: true
      - script: yarn test:unit
        displayName: 'Jest tests'
      - task: PublishCodeCoverageResults@1
        displayName: 'Publish test coverage results'
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/*coverage.xml'
          reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'
      - task: PublishTestResults@1
        displayName: Publish test results
        condition: succeededOrFailed()
        inputs:
          testRunner: JUnit
          testResultsFiles: '$(System.DefaultWorkingDirectory)/coverage/junit.xml'
      - script: yarn seed
        displayName: 'Seed test data'
      - script: yarn cypress run
        displayName: 'Cypress tests'
      - task: PublishTestResults@1
        displayName: Publish test results
        condition: always()
        inputs:
          testRunner: JUnit
          testResultsFiles: '$(System.DefaultWorkingDirectory)/testresults/output-**.xml'
      - task: DockerCompose@0
        displayName: logs
        condition: always()
        inputs:
          action: Run a Docker Compose command
          dockerComposeFile: '$(System.DefaultWorkingDirectory)/docker-compose.yml'
          projectName: $(Build.Repository.Name)
          dockerComposeCommand: "logs" 
          arguments:
            --no-color
            --timestamps
          # detached: true
          # buildImages: true
      # - script: docker-compose -f $(System.DefaultWorkingDirectory)/docker-compose.yml  logs > $(System.DefaultWorkingDirectory)/compose-logs.txt
      #   displayName: Extract Docker Compose logs
      #   condition: always()
      # - task: PublishBuildArtifacts@1
      #   displayName: Publish Docker Compose logs
      #   condition: always()
      #   inputs:
      #     PathtoPublish: '$(System.DefaultWorkingDirectory)/compose-logs.txt'
      #     ArtifactName: compose_logs
      - task: PublishBuildArtifacts@1
        displayName: Publish Cypress videos
        condition: or(failed(), canceled())
        inputs:
          PathtoPublish: '$(System.DefaultWorkingDirectory)/cypress/videos'
          ArtifactName: cypress_videos
      - task: PublishBuildArtifacts@1
        displayName: Publish Cypress snapshot images
        condition: or(failed(), canceled())
        inputs:
          PathtoPublish: '$(System.DefaultWorkingDirectory)/cypress/integration/__image_snapshots__'
          ArtifactName: cypress_snapshots

  - deployment: deploy
    displayName: Deploy images to Docker HUB
    variables:
      YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn
    dependsOn: buildAndTest
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    timeoutInMinutes: "60"
    environment:
      name: DockerHub
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            - task: NodeTool@0
              inputs:
                versionSpec: '16.x'
              displayName: 'Install Node.js'
            - task: Cache@2
              inputs:
                key: 'yarn | "$(Agent.OS)" | yarn.lock'
                restoreKeys: |
                  yarn | "$(Agent.OS)"
                  yarn
                path: $(YARN_CACHE_FOLDER)
              displayName: Cache Yarn packages
            - script: yarn install --frozen-lockfile
              displayName: 'Yarn install'
            - script: yarn build
              displayName: 'Yarn build'
            - task: Docker@2
              displayName: Login to Docker
              inputs:
                command: login
                containerRegistry: dockerHubServiceConnection
            - script: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
              displayName: Pull docker quemi image for buildx
            - script: docker buildx create --name builder --driver docker-container --node build --driver-opt network=host --use
              displayName: Create new buildx builder
            - script: docker buildx inspect --bootstrap
              displayName: Bootstrap BuildX builder
            - script: docker buildx build --platform linux/arm/v7,linux/arm64,linux/amd64 --file ./frontend-core.Dockerfile --tag furystack/multiverse-frontend-core:latest --tag furystack/multiverse-frontend-core:$(Build.BuildNumber) . --push
              displayName: Build Frontend-Core image
            - script: docker buildx build --platform linux/arm/v7,linux/arm64,linux/amd64 --file ./base.Dockerfile --tag furystack/multiverse-base:latest --tag furystack/multiverse-base:$(Build.BuildNumber) . --push
              displayName: Build Base image
            - script: docker buildx build --platform linux/arm/v7,linux/arm64,linux/amd64 --file ./auth.Dockerfile --tag furystack/multiverse-auth:latest --tag furystack/multiverse-auth:$(Build.BuildNumber) . --push
              displayName: Build Auth image
            - script: docker buildx build --platform linux/arm/v7,linux/arm64,linux/amd64 --file ./dashboard.Dockerfile --tag furystack/multiverse-dashboard:latest --tag furystack/multiverse-dashboard:$(Build.BuildNumber) . --push
              displayName: Build Dashboard image
            - script: docker buildx build --platform linux/arm/v7,linux/arm64,linux/amd64 --file ./diag.Dockerfile --tag furystack/multiverse-diag:latest --tag furystack/multiverse-diag:$(Build.BuildNumber) . --push
              displayName: Build Diag image
            - script: docker buildx build --platform linux/arm/v7,linux/arm64,linux/amd64 --file ./media.Dockerfile --tag furystack/multiverse-media:latest --tag furystack/multiverse-media:$(Build.BuildNumber) . --push
              displayName: Build Media image
            - script: docker buildx build --platform linux/arm/v7,linux/arm64,linux/amd64 --file ./media-encoder.Dockerfile --tag furystack/multiverse-media-encoder:latest --tag furystack/multiverse-media-encoder:$(Build.BuildNumber) . --push
              displayName: Build Media Encoder worker image
            - script: docker buildx build --platform linux/arm/v7,linux/arm64,linux/amd64 --file ./xpense.Dockerfile --tag furystack/multiverse-xpense:latest --tag furystack/multiverse-xpense:$(Build.BuildNumber) . --push
              displayName: Build Xpense image
