version: '3'
services:
  mongo:
    image: 'mongo'
    ports:
      - '27017:27017'
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  multiverse-auth:
    image: furystack/multiverse-auth
    ports:
      - 9090:9090
  multiverse-dashboard:
    image: furystack/multiverse-dashboard
    ports:
      - 9094:9094
  multiverse-diag:
    image: furystack/multiverse-diag
    ports:
      - 9091:9091
  multiverse-media:
    image: furystack/multiverse-media
    ports:
      - 9093:9093
  multiverse-xpense:
    image: furystack/multiverse-xpense
    ports:
      - 9092:9092
  multiverse-frontend-core:
    image: furystack/multiverse-frontend-core
    environment:
      - API_ROOT_AUTH=http://localhost:9090
      - API_ROOT_DASHBOARD=http://localhost:9094
      - API_ROOT_DIAG=http://localhost:9091
      - API_ROOT_MEDIA=http://localhost:9093
      - API_ROOT_XPENSE=http://localhost:9092
    ports:
      - 8080:8080