version: '3'
services:
  # nginx:
  #   depends_on:
  #     - multiverse-auth
  #     - multiverse-dashboard
  #     - multiverse-diag
  #     - multiverse-frontend-core
  #     - multiverse-media
  #   image: 'nginx:alpine'
  #   volumes:
  #     - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
  #   ports:
  #     - 80:80
  mongo:
    image: 'mongo'
    ports:
      - '27017:27017'
    restart: unless-stopped
    volumes:
      - multiverse-dev-db:/data/db
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped
  multiverse-auth:
    depends_on:
      - mongo
    image: furystack/multiverse-auth
    environment:
      - MONGO_URL=mongodb://mongo:27017
    ports:
      - 9090:9090
  multiverse-dashboard:
    depends_on:
      - mongo
    image: furystack/multiverse-dashboard
    environment:
      - MONGO_URL=mongodb://mongo:27017
    ports:
      - 9094:9094
  multiverse-diag:
    depends_on:
      - mongo
    image: furystack/multiverse-diag
    environment:
      - MONGO_URL=mongodb://mongo:27017
    ports:
      - 9091:9091
  multiverse-media:
    depends_on:
      - rabbitmq
      - mongo
    image: furystack/multiverse-media
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - RABBITMQ_HOST=amqp://rabbitmq?connection_timeout=30
    ports:
      - 9093:9093
  multiverse-frontend-core:
    image: furystack/multiverse-frontend-core
    environment:
      - API_ROOT_AUTH=http://localhost:9090
      - API_ROOT_DASHBOARD=http://localhost:9094
      - API_ROOT_DIAG=http://localhost:9091
      - API_ROOT_MEDIA=http://localhost:9093
    ports:
      - 8080:8080

volumes:
  multiverse-dev-db: