export * as apis from './apis'
export * from './entity-serializer'
export * as auth from './auth'
export * as diag from './diag'
export * as xpense from './xpense'
export * as media from './media'
export * from './endpoints'
export * as dashboard from './dashboard'
export * from './services'
export * from './owner'

import * as authSchema from './json-schemas-auth.json'
import * as dashboardSchema from './json-schemas-dashboard.json'
import * as diagSchema from './json-schemas-diag.json'
import * as mediaSchema from './json-schemas-media.json'
import * as xpenseSchema from './json-schemas-xpense.json'
export { authSchema, dashboardSchema, diagSchema, mediaSchema, xpenseSchema }
